# Site Settings
title: Jekyll & Bootstrap 4
email: adamjgomez@gmail.com
description: >
  Jekyll & Bootstrap 4
baseurl: ""
url: "http://localhost:4000"
twitter_username:
github_username:  adamjgomez
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
