# Site Settings
title: Jekyll & Bootstrap 4
email: psauerbeck@gmail.com
description: >
  Jekyll & Bootstrap 4
baseurl: "/jekyll-bootstrap-4"
url: "http://pmsaue0.github.io"
twitter_username:
github_username:  pmsaue0
# Build Settings
sass:
  sass_dir:
include: ['_pages']
kramdown:
  input: GFM